#!/bin/bash

function pgrep(){
	exe="$1"
	shift
	arg="$*"
	ps0=`/bin/pgrep "$exe"`
	rc=$?
	ps2=`echo "$ps1"`
	ps3=`echo "$ps2" |xargs ps $arg`
	if [ "$rc" ==  "0" ]; then
		echo "$ps3"
	else
		echo `tput setaf 3`
		echo "Process Not found"
		echo `tput setaf 0`
	fi
}
